package com.seesea.seesealogin.mapper;

import com.seesea.seesealogin.model.po.LoginPo;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.springframework.stereotype.Service;

@Mapper
public interface LoginPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_login
     *
     * @mbg.generated Tue Oct 30 22:38:59 CST 2018
     */
    int deleteByPrimaryKey(@Param("userId") String userId, @Param("loginAccount") String loginAccount);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_login
     *
     * @mbg.generated Tue Oct 30 22:38:59 CST 2018
     */
    int insert(LoginPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_login
     *
     * @mbg.generated Tue Oct 30 22:38:59 CST 2018
     */
    LoginPo selectByPrimaryKey(@Param("userId") String userId, @Param("loginAccount") String loginAccount);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_login
     *
     * @mbg.generated Tue Oct 30 22:38:59 CST 2018
     */
    List<LoginPo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_login
     *
     * @mbg.generated Tue Oct 30 22:38:59 CST 2018
     */
    int updateByPrimaryKey(LoginPo record);

    @Select("select * from tb_login where login_account = #{acct} and statu = '1'")
    LoginPo selectByAcct(String acct);
}