package com.seesea.seesealogin.mapper;

import com.seesea.seesealogin.model.po.LoginLogPo;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface LoginLogPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_login_log
     *
     * @mbg.generated Tue Oct 30 22:43:32 CST 2018
     */
    int deleteByPrimaryKey(String loginId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_login_log
     *
     * @mbg.generated Tue Oct 30 22:43:32 CST 2018
     */
    int insert(LoginLogPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_login_log
     *
     * @mbg.generated Tue Oct 30 22:43:32 CST 2018
     */
    LoginLogPo selectByPrimaryKey(String loginId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_login_log
     *
     * @mbg.generated Tue Oct 30 22:43:32 CST 2018
     */
    List<LoginLogPo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_login_log
     *
     * @mbg.generated Tue Oct 30 22:43:32 CST 2018
     */
    int updateByPrimaryKey(LoginLogPo record);
}