package com.seesea.seesealogin.model.po;

import java.io.Serializable;
import java.util.Date;

public class LoginPo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_login.user_id
     *
     * @mbg.generated Tue Oct 30 22:38:59 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_login.login_account
     *
     * @mbg.generated Tue Oct 30 22:38:59 CST 2018
     */
    private String loginAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_login.login_pwd
     *
     * @mbg.generated Tue Oct 30 22:38:59 CST 2018
     */
    private String loginPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_login.login_token
     *
     * @mbg.generated Tue Oct 30 22:38:59 CST 2018
     */
    private String loginToken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_login.last_login_time
     *
     * @mbg.generated Tue Oct 30 22:38:59 CST 2018
     */
    private Date lastLoginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_login.statu
     *
     * @mbg.generated Tue Oct 30 22:38:59 CST 2018
     */
    private String statu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_login.remark
     *
     * @mbg.generated Tue Oct 30 22:38:59 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_login
     *
     * @mbg.generated Tue Oct 30 22:38:59 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_login.user_id
     *
     * @return the value of tb_login.user_id
     *
     * @mbg.generated Tue Oct 30 22:38:59 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_login.user_id
     *
     * @param userId the value for tb_login.user_id
     *
     * @mbg.generated Tue Oct 30 22:38:59 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_login.login_account
     *
     * @return the value of tb_login.login_account
     *
     * @mbg.generated Tue Oct 30 22:38:59 CST 2018
     */
    public String getLoginAccount() {
        return loginAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_login.login_account
     *
     * @param loginAccount the value for tb_login.login_account
     *
     * @mbg.generated Tue Oct 30 22:38:59 CST 2018
     */
    public void setLoginAccount(String loginAccount) {
        this.loginAccount = loginAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_login.login_pwd
     *
     * @return the value of tb_login.login_pwd
     *
     * @mbg.generated Tue Oct 30 22:38:59 CST 2018
     */
    public String getLoginPwd() {
        return loginPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_login.login_pwd
     *
     * @param loginPwd the value for tb_login.login_pwd
     *
     * @mbg.generated Tue Oct 30 22:38:59 CST 2018
     */
    public void setLoginPwd(String loginPwd) {
        this.loginPwd = loginPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_login.login_token
     *
     * @return the value of tb_login.login_token
     *
     * @mbg.generated Tue Oct 30 22:38:59 CST 2018
     */
    public String getLoginToken() {
        return loginToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_login.login_token
     *
     * @param loginToken the value for tb_login.login_token
     *
     * @mbg.generated Tue Oct 30 22:38:59 CST 2018
     */
    public void setLoginToken(String loginToken) {
        this.loginToken = loginToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_login.last_login_time
     *
     * @return the value of tb_login.last_login_time
     *
     * @mbg.generated Tue Oct 30 22:38:59 CST 2018
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_login.last_login_time
     *
     * @param lastLoginTime the value for tb_login.last_login_time
     *
     * @mbg.generated Tue Oct 30 22:38:59 CST 2018
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_login.statu
     *
     * @return the value of tb_login.statu
     *
     * @mbg.generated Tue Oct 30 22:38:59 CST 2018
     */
    public String getStatu() {
        return statu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_login.statu
     *
     * @param statu the value for tb_login.statu
     *
     * @mbg.generated Tue Oct 30 22:38:59 CST 2018
     */
    public void setStatu(String statu) {
        this.statu = statu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_login.remark
     *
     * @return the value of tb_login.remark
     *
     * @mbg.generated Tue Oct 30 22:38:59 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_login.remark
     *
     * @param remark the value for tb_login.remark
     *
     * @mbg.generated Tue Oct 30 22:38:59 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_login
     *
     * @mbg.generated Tue Oct 30 22:38:59 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", loginAccount=").append(loginAccount);
        sb.append(", loginPwd=").append(loginPwd);
        sb.append(", loginToken=").append(loginToken);
        sb.append(", lastLoginTime=").append(lastLoginTime);
        sb.append(", statu=").append(statu);
        sb.append(", remark=").append(remark);
        sb.append("]");
        return sb.toString();
    }
}