package com.seesea.seesealogin.model.po;

import java.io.Serializable;
import java.util.Date;

public class LoginLogPo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_login_log.login_id
     *
     * @mbg.generated Tue Oct 30 22:43:32 CST 2018
     */
    private String loginId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_login_log.user_id
     *
     * @mbg.generated Tue Oct 30 22:43:32 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_login_log.login_time
     *
     * @mbg.generated Tue Oct 30 22:43:32 CST 2018
     */
    private Date loginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_login_log.login_token
     *
     * @mbg.generated Tue Oct 30 22:43:32 CST 2018
     */
    private String loginToken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_login_log.remark
     *
     * @mbg.generated Tue Oct 30 22:43:32 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_login_log.login_ip
     *
     * @mbg.generated Tue Oct 30 22:43:32 CST 2018
     */
    private String loginIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_login_log.login_result
     *
     * @mbg.generated Tue Oct 30 22:43:32 CST 2018
     */
    private String loginResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_login_log
     *
     * @mbg.generated Tue Oct 30 22:43:32 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_login_log.login_id
     *
     * @return the value of tb_login_log.login_id
     *
     * @mbg.generated Tue Oct 30 22:43:32 CST 2018
     */
    public String getLoginId() {
        return loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_login_log.login_id
     *
     * @param loginId the value for tb_login_log.login_id
     *
     * @mbg.generated Tue Oct 30 22:43:32 CST 2018
     */
    public void setLoginId(String loginId) {
        this.loginId = loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_login_log.user_id
     *
     * @return the value of tb_login_log.user_id
     *
     * @mbg.generated Tue Oct 30 22:43:32 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_login_log.user_id
     *
     * @param userId the value for tb_login_log.user_id
     *
     * @mbg.generated Tue Oct 30 22:43:32 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_login_log.login_time
     *
     * @return the value of tb_login_log.login_time
     *
     * @mbg.generated Tue Oct 30 22:43:32 CST 2018
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_login_log.login_time
     *
     * @param loginTime the value for tb_login_log.login_time
     *
     * @mbg.generated Tue Oct 30 22:43:32 CST 2018
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_login_log.login_token
     *
     * @return the value of tb_login_log.login_token
     *
     * @mbg.generated Tue Oct 30 22:43:32 CST 2018
     */
    public String getLoginToken() {
        return loginToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_login_log.login_token
     *
     * @param loginToken the value for tb_login_log.login_token
     *
     * @mbg.generated Tue Oct 30 22:43:32 CST 2018
     */
    public void setLoginToken(String loginToken) {
        this.loginToken = loginToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_login_log.remark
     *
     * @return the value of tb_login_log.remark
     *
     * @mbg.generated Tue Oct 30 22:43:32 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_login_log.remark
     *
     * @param remark the value for tb_login_log.remark
     *
     * @mbg.generated Tue Oct 30 22:43:32 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_login_log.login_ip
     *
     * @return the value of tb_login_log.login_ip
     *
     * @mbg.generated Tue Oct 30 22:43:32 CST 2018
     */
    public String getLoginIp() {
        return loginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_login_log.login_ip
     *
     * @param loginIp the value for tb_login_log.login_ip
     *
     * @mbg.generated Tue Oct 30 22:43:32 CST 2018
     */
    public void setLoginIp(String loginIp) {
        this.loginIp = loginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_login_log.login_result
     *
     * @return the value of tb_login_log.login_result
     *
     * @mbg.generated Tue Oct 30 22:43:32 CST 2018
     */
    public String getLoginResult() {
        return loginResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_login_log.login_result
     *
     * @param loginResult the value for tb_login_log.login_result
     *
     * @mbg.generated Tue Oct 30 22:43:32 CST 2018
     */
    public void setLoginResult(String loginResult) {
        this.loginResult = loginResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_login_log
     *
     * @mbg.generated Tue Oct 30 22:43:32 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", loginId=").append(loginId);
        sb.append(", userId=").append(userId);
        sb.append(", loginTime=").append(loginTime);
        sb.append(", loginToken=").append(loginToken);
        sb.append(", remark=").append(remark);
        sb.append(", loginIp=").append(loginIp);
        sb.append(", loginResult=").append(loginResult);
        sb.append("]");
        return sb.toString();
    }
}