package com.seesea.seesealogin.model.po;

import java.io.Serializable;
import java.util.Date;

public class RegisterPo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_register.register_acct
     *
     * @mbg.generated Tue Oct 30 21:18:09 CST 2018
     */
    private String registerAcct;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_register.status
     *
     * @mbg.generated Tue Oct 30 21:18:09 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_register.register_type
     *
     * @mbg.generated Tue Oct 30 21:18:09 CST 2018
     */
    private String registerType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_register.remark
     *
     * @mbg.generated Tue Oct 30 21:18:09 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_register.register_time
     *
     * @mbg.generated Tue Oct 30 21:18:09 CST 2018
     */
    private Date registerTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_register
     *
     * @mbg.generated Tue Oct 30 21:18:09 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_register.register_acct
     *
     * @return the value of tb_register.register_acct
     *
     * @mbg.generated Tue Oct 30 21:18:09 CST 2018
     */
    public String getRegisterAcct() {
        return registerAcct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_register.register_acct
     *
     * @param registerAcct the value for tb_register.register_acct
     *
     * @mbg.generated Tue Oct 30 21:18:09 CST 2018
     */
    public void setRegisterAcct(String registerAcct) {
        this.registerAcct = registerAcct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_register.status
     *
     * @return the value of tb_register.status
     *
     * @mbg.generated Tue Oct 30 21:18:09 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_register.status
     *
     * @param status the value for tb_register.status
     *
     * @mbg.generated Tue Oct 30 21:18:09 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_register.register_type
     *
     * @return the value of tb_register.register_type
     *
     * @mbg.generated Tue Oct 30 21:18:09 CST 2018
     */
    public String getRegisterType() {
        return registerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_register.register_type
     *
     * @param registerType the value for tb_register.register_type
     *
     * @mbg.generated Tue Oct 30 21:18:09 CST 2018
     */
    public void setRegisterType(String registerType) {
        this.registerType = registerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_register.remark
     *
     * @return the value of tb_register.remark
     *
     * @mbg.generated Tue Oct 30 21:18:09 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_register.remark
     *
     * @param remark the value for tb_register.remark
     *
     * @mbg.generated Tue Oct 30 21:18:09 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_register.register_time
     *
     * @return the value of tb_register.register_time
     *
     * @mbg.generated Tue Oct 30 21:18:09 CST 2018
     */
    public Date getRegisterTime() {
        return registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_register.register_time
     *
     * @param registerTime the value for tb_register.register_time
     *
     * @mbg.generated Tue Oct 30 21:18:09 CST 2018
     */
    public void setRegisterTime(Date registerTime) {
        this.registerTime = registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_register
     *
     * @mbg.generated Tue Oct 30 21:18:09 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", registerAcct=").append(registerAcct);
        sb.append(", status=").append(status);
        sb.append(", registerType=").append(registerType);
        sb.append(", remark=").append(remark);
        sb.append(", registerTime=").append(registerTime);
        sb.append("]");
        return sb.toString();
    }
}