package com.seesea.seeseauser.mapper;

import com.seesea.seeseauser.pojo.Address;
import java.util.List;

public interface AddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_address
     *
     * @mbg.generated Tue Oct 02 16:42:40 CST 2018
     */
    int deleteByPrimaryKey(String addressId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_address
     *
     * @mbg.generated Tue Oct 02 16:42:40 CST 2018
     */
    int insert(Address record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_address
     *
     * @mbg.generated Tue Oct 02 16:42:40 CST 2018
     */
    Address selectByPrimaryKey(String addressId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_address
     *
     * @mbg.generated Tue Oct 02 16:42:40 CST 2018
     */
    List<Address> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_address
     *
     * @mbg.generated Tue Oct 02 16:42:40 CST 2018
     */
    int updateByPrimaryKey(Address record);
}