package com.seesea.seeseauser.pojo;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.user_id
     *
     * @mbg.generated Tue Oct 02 16:42:40 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.user_sex
     *
     * @mbg.generated Tue Oct 02 16:42:40 CST 2018
     */
    private Integer userSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.user_portrait
     *
     * @mbg.generated Tue Oct 02 16:42:40 CST 2018
     */
    private String userPortrait;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.user_nickname
     *
     * @mbg.generated Tue Oct 02 16:42:40 CST 2018
     */
    private String userNickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.user_signature
     *
     * @mbg.generated Tue Oct 02 16:42:40 CST 2018
     */
    private String userSignature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.user_email
     *
     * @mbg.generated Tue Oct 02 16:42:40 CST 2018
     */
    private String userEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.user_birthday
     *
     * @mbg.generated Tue Oct 02 16:42:40 CST 2018
     */
    private Date userBirthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.user_vip
     *
     * @mbg.generated Tue Oct 02 16:42:40 CST 2018
     */
    private Integer userVip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.user_coin
     *
     * @mbg.generated Tue Oct 02 16:42:40 CST 2018
     */
    private Integer userCoin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.user_phone
     *
     * @mbg.generated Tue Oct 02 16:42:40 CST 2018
     */
    private String userPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.user_passward
     *
     * @mbg.generated Tue Oct 02 16:42:40 CST 2018
     */
    private String userPassward;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.user_statu
     *
     * @mbg.generated Tue Oct 02 16:42:40 CST 2018
     */
    private Byte userStatu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_user
     *
     * @mbg.generated Tue Oct 02 16:42:40 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_id
     *
     * @return the value of tb_user.user_id
     *
     * @mbg.generated Tue Oct 02 16:42:40 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_id
     *
     * @param userId the value for tb_user.user_id
     *
     * @mbg.generated Tue Oct 02 16:42:40 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_sex
     *
     * @return the value of tb_user.user_sex
     *
     * @mbg.generated Tue Oct 02 16:42:40 CST 2018
     */
    public Integer getUserSex() {
        return userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_sex
     *
     * @param userSex the value for tb_user.user_sex
     *
     * @mbg.generated Tue Oct 02 16:42:40 CST 2018
     */
    public void setUserSex(Integer userSex) {
        this.userSex = userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_portrait
     *
     * @return the value of tb_user.user_portrait
     *
     * @mbg.generated Tue Oct 02 16:42:40 CST 2018
     */
    public String getUserPortrait() {
        return userPortrait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_portrait
     *
     * @param userPortrait the value for tb_user.user_portrait
     *
     * @mbg.generated Tue Oct 02 16:42:40 CST 2018
     */
    public void setUserPortrait(String userPortrait) {
        this.userPortrait = userPortrait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_nickname
     *
     * @return the value of tb_user.user_nickname
     *
     * @mbg.generated Tue Oct 02 16:42:40 CST 2018
     */
    public String getUserNickname() {
        return userNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_nickname
     *
     * @param userNickname the value for tb_user.user_nickname
     *
     * @mbg.generated Tue Oct 02 16:42:40 CST 2018
     */
    public void setUserNickname(String userNickname) {
        this.userNickname = userNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_signature
     *
     * @return the value of tb_user.user_signature
     *
     * @mbg.generated Tue Oct 02 16:42:40 CST 2018
     */
    public String getUserSignature() {
        return userSignature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_signature
     *
     * @param userSignature the value for tb_user.user_signature
     *
     * @mbg.generated Tue Oct 02 16:42:40 CST 2018
     */
    public void setUserSignature(String userSignature) {
        this.userSignature = userSignature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_email
     *
     * @return the value of tb_user.user_email
     *
     * @mbg.generated Tue Oct 02 16:42:40 CST 2018
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_email
     *
     * @param userEmail the value for tb_user.user_email
     *
     * @mbg.generated Tue Oct 02 16:42:40 CST 2018
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_birthday
     *
     * @return the value of tb_user.user_birthday
     *
     * @mbg.generated Tue Oct 02 16:42:40 CST 2018
     */
    public Date getUserBirthday() {
        return userBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_birthday
     *
     * @param userBirthday the value for tb_user.user_birthday
     *
     * @mbg.generated Tue Oct 02 16:42:40 CST 2018
     */
    public void setUserBirthday(Date userBirthday) {
        this.userBirthday = userBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_vip
     *
     * @return the value of tb_user.user_vip
     *
     * @mbg.generated Tue Oct 02 16:42:40 CST 2018
     */
    public Integer getUserVip() {
        return userVip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_vip
     *
     * @param userVip the value for tb_user.user_vip
     *
     * @mbg.generated Tue Oct 02 16:42:40 CST 2018
     */
    public void setUserVip(Integer userVip) {
        this.userVip = userVip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_coin
     *
     * @return the value of tb_user.user_coin
     *
     * @mbg.generated Tue Oct 02 16:42:40 CST 2018
     */
    public Integer getUserCoin() {
        return userCoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_coin
     *
     * @param userCoin the value for tb_user.user_coin
     *
     * @mbg.generated Tue Oct 02 16:42:40 CST 2018
     */
    public void setUserCoin(Integer userCoin) {
        this.userCoin = userCoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_phone
     *
     * @return the value of tb_user.user_phone
     *
     * @mbg.generated Tue Oct 02 16:42:40 CST 2018
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_phone
     *
     * @param userPhone the value for tb_user.user_phone
     *
     * @mbg.generated Tue Oct 02 16:42:40 CST 2018
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_passward
     *
     * @return the value of tb_user.user_passward
     *
     * @mbg.generated Tue Oct 02 16:42:40 CST 2018
     */
    public String getUserPassward() {
        return userPassward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_passward
     *
     * @param userPassward the value for tb_user.user_passward
     *
     * @mbg.generated Tue Oct 02 16:42:40 CST 2018
     */
    public void setUserPassward(String userPassward) {
        this.userPassward = userPassward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_statu
     *
     * @return the value of tb_user.user_statu
     *
     * @mbg.generated Tue Oct 02 16:42:40 CST 2018
     */
    public Byte getUserStatu() {
        return userStatu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_statu
     *
     * @param userStatu the value for tb_user.user_statu
     *
     * @mbg.generated Tue Oct 02 16:42:40 CST 2018
     */
    public void setUserStatu(Byte userStatu) {
        this.userStatu = userStatu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbg.generated Tue Oct 02 16:42:40 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", userSex=").append(userSex);
        sb.append(", userPortrait=").append(userPortrait);
        sb.append(", userNickname=").append(userNickname);
        sb.append(", userSignature=").append(userSignature);
        sb.append(", userEmail=").append(userEmail);
        sb.append(", userBirthday=").append(userBirthday);
        sb.append(", userVip=").append(userVip);
        sb.append(", userCoin=").append(userCoin);
        sb.append(", userPhone=").append(userPhone);
        sb.append(", userPassward=").append(userPassward);
        sb.append(", userStatu=").append(userStatu);
        sb.append("]");
        return sb.toString();
    }
}