package com.seesea.seeseainteraction.mapper;

import com.seesea.seeseainteraction.pojo.Friend;
import java.util.List;

public interface FriendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend
     *
     * @mbg.generated Tue Oct 02 16:46:59 CST 2018
     */
    int deleteByPrimaryKey(String friendId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend
     *
     * @mbg.generated Tue Oct 02 16:46:59 CST 2018
     */
    int insert(Friend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend
     *
     * @mbg.generated Tue Oct 02 16:46:59 CST 2018
     */
    Friend selectByPrimaryKey(String friendId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend
     *
     * @mbg.generated Tue Oct 02 16:46:59 CST 2018
     */
    List<Friend> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend
     *
     * @mbg.generated Tue Oct 02 16:46:59 CST 2018
     */
    int updateByPrimaryKey(Friend record);
}