package com.seesea.seeseainteraction.mapper;

import com.seesea.seeseainteraction.pojo.Praise;
import java.util.List;

public interface PraiseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_praise
     *
     * @mbg.generated Tue Oct 02 16:46:59 CST 2018
     */
    int deleteByPrimaryKey(Long praiseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_praise
     *
     * @mbg.generated Tue Oct 02 16:46:59 CST 2018
     */
    int insert(Praise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_praise
     *
     * @mbg.generated Tue Oct 02 16:46:59 CST 2018
     */
    Praise selectByPrimaryKey(Long praiseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_praise
     *
     * @mbg.generated Tue Oct 02 16:46:59 CST 2018
     */
    List<Praise> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_praise
     *
     * @mbg.generated Tue Oct 02 16:46:59 CST 2018
     */
    int updateByPrimaryKey(Praise record);
}