package com.seesea.seeseasms.mapper;

import com.seesea.seeseasms.model.po.SmsLogPo;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface SmsLogPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sms_log
     *
     * @mbg.generated Fri Oct 26 22:29:02 CST 2018
     */
    int deleteByPrimaryKey(@Param("smsId") String smsId, @Param("reqId") String reqId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sms_log
     *
     * @mbg.generated Fri Oct 26 22:29:02 CST 2018
     */
    int insert(SmsLogPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sms_log
     *
     * @mbg.generated Fri Oct 26 22:29:02 CST 2018
     */
    SmsLogPo selectByPrimaryKey(@Param("smsId") String smsId, @Param("reqId") String reqId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sms_log
     *
     * @mbg.generated Fri Oct 26 22:29:02 CST 2018
     */
    List<SmsLogPo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sms_log
     *
     * @mbg.generated Fri Oct 26 22:29:02 CST 2018
     */
    int updateByPrimaryKey(SmsLogPo record);
}