package com.seesea.seeseasms.mapper;

import com.seesea.seeseasms.model.po.SmsSendAndCheckPo;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface SmsSendAndCheckPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sms_send_check
     *
     * @mbg.generated Thu Oct 25 23:23:56 CST 2018
     */
    int deleteByPrimaryKey(String smsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sms_send_check
     *
     * @mbg.generated Thu Oct 25 23:23:56 CST 2018
     */
    int insert(SmsSendAndCheckPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sms_send_check
     *
     * @mbg.generated Thu Oct 25 23:23:56 CST 2018
     */
    SmsSendAndCheckPo selectByPrimaryKey(String smsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sms_send_check
     *
     * @mbg.generated Thu Oct 25 23:23:56 CST 2018
     */
    List<SmsSendAndCheckPo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sms_send_check
     *
     * @mbg.generated Thu Oct 25 23:23:56 CST 2018
     */
    int updateByPrimaryKey(SmsSendAndCheckPo record);
}