package com.seesea.seeseainteraction.pojo;

import java.io.Serializable;

public class Friend implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_friend.friend_id
     *
     * @mbg.generated Tue Oct 02 16:46:59 CST 2018
     */
    private String friendId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_friend.friend_fan_id
     *
     * @mbg.generated Tue Oct 02 16:46:59 CST 2018
     */
    private String friendFanId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_friend.friend_attention_id
     *
     * @mbg.generated Tue Oct 02 16:46:59 CST 2018
     */
    private String friendAttentionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_friend
     *
     * @mbg.generated Tue Oct 02 16:46:59 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_friend.friend_id
     *
     * @return the value of tb_friend.friend_id
     *
     * @mbg.generated Tue Oct 02 16:46:59 CST 2018
     */
    public String getFriendId() {
        return friendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_friend.friend_id
     *
     * @param friendId the value for tb_friend.friend_id
     *
     * @mbg.generated Tue Oct 02 16:46:59 CST 2018
     */
    public void setFriendId(String friendId) {
        this.friendId = friendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_friend.friend_fan_id
     *
     * @return the value of tb_friend.friend_fan_id
     *
     * @mbg.generated Tue Oct 02 16:46:59 CST 2018
     */
    public String getFriendFanId() {
        return friendFanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_friend.friend_fan_id
     *
     * @param friendFanId the value for tb_friend.friend_fan_id
     *
     * @mbg.generated Tue Oct 02 16:46:59 CST 2018
     */
    public void setFriendFanId(String friendFanId) {
        this.friendFanId = friendFanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_friend.friend_attention_id
     *
     * @return the value of tb_friend.friend_attention_id
     *
     * @mbg.generated Tue Oct 02 16:46:59 CST 2018
     */
    public String getFriendAttentionId() {
        return friendAttentionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_friend.friend_attention_id
     *
     * @param friendAttentionId the value for tb_friend.friend_attention_id
     *
     * @mbg.generated Tue Oct 02 16:46:59 CST 2018
     */
    public void setFriendAttentionId(String friendAttentionId) {
        this.friendAttentionId = friendAttentionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend
     *
     * @mbg.generated Tue Oct 02 16:46:59 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", friendId=").append(friendId);
        sb.append(", friendFanId=").append(friendFanId);
        sb.append(", friendAttentionId=").append(friendAttentionId);
        sb.append("]");
        return sb.toString();
    }
}