server:
  port: 8000

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    register-withEureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka/

spring:
  application:
    name: seesea-eurka
  cloud:
    inetutils:
      timeout-seconds: 10
